apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
